image: docker:stable

before_script:
- apk add --no-cache py-pip
- pip install --no-cache-dir docker-compose
- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

.dedicated-runner: &dedicated-runner
  tags:
  - docker
  - linux

build:
  <<: *dedicated-runner
  stage: build
  script:
  - docker-compose -f docker-compose.build.yml -f docker-compose.gitlab.yml build --pull
  - docker-compose -f docker-compose.build.yml -f docker-compose.gitlab.yml push
