jobs:
  include:
    - stage: Test
      services:
        - docker
      sudo: required
      env:
        - COMPOSE_FILE=docker-compose.yml:.docker/service.redis.yml:.docker/env.prod.yml:.docker/build.yml
        - DB_IMAGE=mariadb:10.2
        - FRONTEND_NETWORK=frontend
        - MYSQL_ROOT_PASSWORD=mySecurePassword
        - REDIS=1
        - RESTART=no
        - TRUSTED_HOSTS_PATTERN=.*
        - TYPO3_INSTALL_ADMIN_USER=travis
        - TYPO3_INSTALL_ADMIN_PASSWORD=mySecurePassword
        - TYPO3_INSTALL_SITE_NAME=Travis Test
        - TYPO3_INSTALL_SITE_SETUP_TYPE=site
        - TYPO3_INSTALL_WEB_SERVER_CONFIG=none
        - VHOST=typo3.localhost
      before_script:
        - docker-compose up -d --build
      script:
        - docker-compose exec -u www-data typo3 typo3cms install:setup --no-interaction
      after_script:
        - docker-compose down -v
