version: "3.3"
services:
  typo3:
    networks:
    - 2_mailhog

  mailhog:
    image: mailhog/mailhog
    networks:
    - 2_mailhog
    - 2_frontend
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:mail.${VHOST}"
    - "traefik.port=8025"

networks:
  2_mailhog:
