version: '3.5'
services:
  db:
    networks:
      adminer-db:

  adminer:
    image: adminer
    networks:
      adminer-db:
      2_frontend:
    environment:
      VIRTUAL_HOST: adminer.${VHOST}
      VIRTUAL_PORT: '8080'
    labels:
      traefik.docker.network: ${FRONTEND_NETWORK}
      traefik.enable: "true"
      traefik.frontend.rule: Host:adminer.${VHOST}
      traefik.port: '8080'

networks:
  adminer-db:
