services:
  web:
    image: ${WEB_IMAGE}
    networks:
      frontend:
      web-typo3:
        aliases:
        - ${VHOST}
    depends_on:
    - typo3
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=${FRONTEND_NETWORK:-frontend}"
    - "traefik.http.routers.web-http-${COMPOSE_PROJECT_NAME}.rule=Host(`${VHOST}`)"
    - "traefik.http.routers.web-http-${COMPOSE_PROJECT_NAME}.entrypoints=${TRAEFIK_ENTRYPOINT_HTTP}"
    - "traefik.http.routers.web-https-${COMPOSE_PROJECT_NAME}.rule=Host(`${VHOST}`)"
    - "traefik.http.routers.web-https-${COMPOSE_PROJECT_NAME}.entrypoints=${TRAEFIK_ENTRYPOINT_HTTPS}"
    - "traefik.http.routers.web-https-${COMPOSE_PROJECT_NAME}.tls=true"
    - "traefik.http.services.web-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
    restart: "${RESTART}"

  typo3:
    image: ${TYPO3_IMAGE}
    networks:
      web-typo3:
    environment:
      TRUSTED_HOSTS_PATTERN:
    restart: "${RESTART}"

networks:
  web-typo3:
  frontend:
    external: true
    name: ${FRONTEND_NETWORK:-frontend}
