services:
  db:
    networks:
      adminer-db:

  adminer:
    image: adminer
    depends_on:
    - db
    networks:
      adminer-db:
      frontend:
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=${FRONTEND_NETWORK:-frontend}"
    - "traefik.http.routers.adminer-http-${COMPOSE_PROJECT_NAME}.rule=Host(`adminer-${VHOST}`)"
    - "traefik.http.routers.adminer-http-${COMPOSE_PROJECT_NAME}.entrypoints=${TRAEFIK_ENTRYPOINT_HTTP}"
    - "traefik.http.routers.adminer-https-${COMPOSE_PROJECT_NAME}.rule=Host(`adminer-${VHOST}`)"
    - "traefik.http.routers.adminer-https-${COMPOSE_PROJECT_NAME}.entrypoints=${TRAEFIK_ENTRYPOINT_HTTPS}"
    - "traefik.http.routers.adminer-https-${COMPOSE_PROJECT_NAME}.tls=true"
    - "traefik.http.services.adminer-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"
    restart: "${RESTART}"

networks:
  adminer-db:
