services:
  typo3:
    environment:
      SMTP_SERVER: mailhog
      SMTP_PORT: "1025"
    networks:
      typo3-mailhog:

  mailhog:
    image: mailhog/mailhog
    networks:
      typo3-mailhog:
      frontend:
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=${FRONTEND_NETWORK:-frontend}"
    - "traefik.http.routers.mailhog-http-${COMPOSE_PROJECT_NAME}.rule=Host(`mailhog-${VHOST}`)"
    - "traefik.http.routers.mailhog-http-${COMPOSE_PROJECT_NAME}.entrypoints=${TRAEFIK_ENTRYPOINT_HTTP}"
    - "traefik.http.routers.mailhog-https-${COMPOSE_PROJECT_NAME}.rule=Host(`mailhog-${VHOST}`)"
    - "traefik.http.routers.mailhog-https-${COMPOSE_PROJECT_NAME}.entrypoints=${TRAEFIK_ENTRYPOINT_HTTPS}"
    - "traefik.http.routers.mailhog-https-${COMPOSE_PROJECT_NAME}.tls=true"
    - "traefik.http.services.mailhog-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8025"
    restart: "${RESTART}"

networks:
  typo3-mailhog:
