name: Build and push Docker images

on:
  push:

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
        - branch: main
          typo3-version: dev-master
        - branch: 11.x
          typo3-version: 11
        - branch: 10.x
          typo3-version: 10
        - branch: 9.x
          typo3-version: 9
        
    env:
      IMAGE_NAME: t3easy/typo3
      PLATFORMS: linux/amd64,linux/arm64
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push web-development
      uses: docker/build-push-action@v2
      with:
        build-args: |
          TARGET_ENVIRONMENT=development
        context: .
        file: .docker/Dockerfile
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:web-${{ matrix.typo3-version }}-dev
        target: web-development
        platforms: ${{ env.PLATFORMS }}
        push: true

    - name: Build and push php-development
      uses: docker/build-push-action@v2
      with:
        build-args: |
          TARGET_ENVIRONMENT=development
        context: .
        file: .docker/Dockerfile
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:typo3-${{ matrix.typo3-version }}-dev
        target: php-development
        platforms: ${{ env.PLATFORMS }}
        push: true

    - name: Build and push web-production
      uses: docker/build-push-action@v2
      with:
        context: .
        file: .docker/Dockerfile
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:web-${{ matrix.typo3-version }}
        target: web-production
        platforms: ${{ env.PLATFORMS }}
        push: true

    - name: Build and push php-production
      uses: docker/build-push-action@v2
      with:
        context: .
        file: .docker/Dockerfile
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:typo3-${{ matrix.typo3-version }}
        target: php-production
        platforms: ${{ env.PLATFORMS }}
        push: true
