name: Build and push Docker images

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: t3easy/typo3
      PLATFORMS: linux/amd64,linux/arm64
      TYPO3_MAJOR_VERSION: dev-master
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push web-development
      uses: docker/build-push-action@v2
      with:
        build-args: |
          TARGET_ENVIRONMENT=development
        context: .
        file: .docker/Dockerfile
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:web-${{ env.TYPO3_MAJOR_VERSION }}-dev
        target: web-development
        platforms: ${{ env.PLATFORMS }}
        push: true

    - name: Build and push php-development
      uses: docker/build-push-action@v2
      with:
        build-args: |
          TARGET_ENVIRONMENT=development
        context: .
        file: .docker/Dockerfile
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:typo3-${{ env.TYPO3_MAJOR_VERSION }}-dev
        target: php-development
        platforms: ${{ env.PLATFORMS }}
        push: true

    - name: Build and push web-production
      uses: docker/build-push-action@v2
      with:
        context: .
        file: .docker/Dockerfile
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:web-${{ env.TYPO3_MAJOR_VERSION }}
        target: web-production
        platforms: ${{ env.PLATFORMS }}
        push: true

    - name: Build and push php-production
      uses: docker/build-push-action@v2
      with:
        context: .
        file: .docker/Dockerfile
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:typo3-${{ env.TYPO3_MAJOR_VERSION }}
        target: php-production
        platforms: ${{ env.PLATFORMS }}
        push: true
